### ISSUE TITLE
mount point

### ISSUE THREAD

**Issue by ZACK1809** [JohnTroony/LUKS-OPs#4]
I am currently attempting to use your script in Debian but I am having difficulty specifying a mount point. Everytime I declare a mount point i.e. /media/tmp, the volume doesn't mount. Everything works as expected using the default /media/luks_random option.

For example encrypted volume /usr/myfiles.
Specified mount point /media/tmp

I am prompted for a password and the script completes but the volume is not being mounted however the volume then appears under the system menu as myfiles. If I double click on the volume myfiles displayed under system it auto mounts to /media/myfiles.

I am not sure if there is an issue with defining mount points or if I am just misinterpreting things but any help on this would be great.

Thanks!
ZACK

**Comment by JohnTroony** [comment]
Hey @ZACK1809, 

Apologies for taking time to respond to this one. I'm not maintaining the project but I'd like to help if you specify the OS (version, release and your desktop environment). For your case,  **/media/tmp** must exist! You can't mount the encrypted volume in nonexistent directory.

Btw, you can simply use **./luksOps new disk_Name Size_in_numbers** to create a LUKS volume.
 **./luksOps mount /path/to/device   /existing/mount/point** to mount a volume and finally,
**./luksOps unmount-all** to unmount mounted LUKS volumes. 

I'll close this.
